//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDiabloIII.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilidad
    {
        #region VARIABLES PRIVADAS

        private int _idHabilidad, _idPersonaje;

        private string _nombre, _tipo;

        #endregion



        #region METODOS GET SET

        public int idHabilidad { get => this._idHabilidad; set => this._idHabilidad = value; }
        public string nombre { get => _nombre; set => _nombre = value; }
        public string tipo { get => _tipo; set => _tipo = value; }

        public int idPersonaje { get => _idPersonaje; set => _idPersonaje = value; }

        public virtual Personaje Personaje { get; set; }

        #endregion
    }
}
