//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDiabloIII.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {

        private int _idItem, _idPersonaje;
        private string _nombre, _tipo;

    
        public virtual Personaje Personaje { get; set; }
        public int idItem { get => _idItem; set => _idItem = value; }
        public int idPersonaje { get => _idPersonaje; set => _idPersonaje = value; }
        public string nombre { get => _nombre; set => _nombre = value; }
        public string tipo { get => _tipo; set => _tipo = value; }
    }
}
